name: Test Vault RSA Key

on: [push]

jobs:
  test-vault-key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch RSA Key from Vault
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}  # Ensure you have set this in GitHub secrets
        run: |
          echo "Fetching RSA Key from Vault..."
          rsa_key=$(vault kv get -field=private_key secret/rsa_keys)
          echo "RSA Key fetched successfully."  # Avoid printing sensitive data in production

          # Optionally save the key to a file for later use
          echo "$rsa_key" > private_key.pem
          echo "Private key saved to private_key.pem."

      - name: Validate RSA Key Format
        run: |
          echo "Validating RSA Key format..."
          if openssl rsa -check -in private_key.pem; then
            echo "RSA Key format is valid."
          else
            echo "RSA Key format is invalid!" >&2
            exit 1
          fi

      - name: Use RSA Key (Example)
        run: |
          echo "Using the RSA Key..."
          # Here, you can add any command that utilizes the RSA key.
          # For example, sign a message or verify a signature.
