name: Fetch and Convert PEM Key

on: [push]

jobs:
  fetch-pem-key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget

      - name: Install Vault CLI
        run: |
          wget https://releases.hashicorp.com/vault/1.11.5/vault_1.11.5_linux_amd64.zip
          unzip vault_1.11.5_linux_amd64.zip
          sudo mv vault /usr/local/bin/
          chmod +x /usr/local/bin/vault
          vault -v

      - name: Set Vault Address and Namespace
        run: |
          echo "VAULT_ADDR=https://vault-cluster-public-vault-7f79ed77.cee56294.z1.hashicorp.cloud:8200" >> $GITHUB_ENV
          echo "VAULT_NAMESPACE=admin" >> $GITHUB_ENV

      - name: Fetch and Convert PEM Key to .env Format
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
          VAULT_ADDR: ${{ env.VAULT_ADDR }}
          VAULT_NAMESPACE: ${{ env.VAULT_NAMESPACE }}
        run: |
          # Fetch the private key from Vault
          pem_key=$(vault kv get -field=private_key secrets/rsa_keys)
          
          # Convert the PEM key to .env format (single line)
          pem_key_env=$(echo "$pem_key" | awk 'NF {sub(/\r/, ""); printf "%s\\n", $0}' | sed 's/$/\\n/;s/^/"/;s/$/"/')
          
          # Save to .env file
          echo "PEM_KEY=$pem_key_env" > .env
          echo ".env file created with PEM_KEY."
